### ISSUE TITLE
Belt specific logfile process

### ISSUE THREAD

**Issue by MABatin** [MAIMLab-DU/FeMo_MLOps-CDK#48]
#### **Description**
The Lambda function needs to process S3 log files, extract the belt type from folder structure `<beltType>/<deviceId>/<logfileName>`. Based on the determined belt type, the Lambda function should generate a `manifest-<beltType>.json` file and upload it to a manifest S3 bucket.

This enhancement streamlines the processing of log files for different belt types and organizes the output manifest files appropriately.

---

#### **Tasks**
- [x] **Separate bucket/directory for each belt type and generate manifest file**:
  - Update lambda function to map `A_type`, `B_type`, `C_type` directories to belt types.
  - Map `<beltType>/<deviceId>/<logfile.dat>` folder structure
  - Create a JSON file named `manifest-<beltType>.json`.
  - Include relevant metadata, such as the device ID and belt type, in the manifest.

- [x] **Upload Manifest File to Manifest Bucket**:
  - Store the generated manifest file in a designated S3 manifest bucket.
  - Ensure the manifest file is stored in an appropriate folder or prefix structure.
  - 
- [x] **Update `modelDeploymentStack`**:
  - Update request data: 
  ```
  s3Key: str,
  beltType: [A, B, C],
  reEval: Optional[bool]
  ```
  - `inferenceModelFunction` will select model based on `beltType` provided
  - Same API gateway, i.e. `api.example.com`
- [x] **Error Handling and Logging**:
  - Log relevant information for debugging and monitoring.
