### ISSUE TITLE
Update Model Deployment Stack

### ISSUE THREAD

**Issue by MABatin** [MAIMLab-DU/FeMo_MLOps-CDK#5]
# Tasks to Implement

## **1. Configurable Endpoint Instance Type and Count**
- [x] Make the SageMaker endpoint instance type and count configurable through input parameters or environment variables.

---

## **2. Remove `consumers/online` Module**
- [x] Remove the `consumers/online` module from the project as it is not needed right now.

---

## **3. Update `pipelineModelFunction`**
- [x] Update the runtime for the `pipelineModelFunction` Lambda function to **Python 3.10**.
- [x] Add a GSI for `jobId` to `InferenceResultTable`

---

## **4. Connect SageMaker Endpoint to API Gateway**
- Refer to these resources for implementation:
  - [Blog Guide](https://aws.amazon.com/blogs/machine-learning/creating-a-machine-learning-powered-rest-api-with-amazon-api-gateway-mapping-templates-and-amazon-sagemaker/)
  - [Documentation](https://docs.aws.amazon.com/solutions/latest/constructs/aws-apigateway-sagemakerendpoint.html)
  - [Example](https://github.com/aws-samples/serverless-patterns/tree/main/apigw-lambda-sagemaker-jumpstartendpoint-cdk-python)
  
### Subtasks:
- [x] Set up an **API Gateway** integration with the **SageMaker Endpoint**.

---

### **POST Method**:
- [x] Accepts parameters:
  - `s3Key: str`
  - `reEval: Optional[bool]`
- **Logic**:
  ```python
  if s3Key in dynamoDbTable:
      if not reEval:
          return record[sorted(timeStamp)[-1]]
      else:
          return sm_invokeEndpoint(s3Key)
  return sm_invokeEndpoint(s3Key)

### **GET Method:**
- [x] Accepts jobId as a parameter in the URL path.
- **Logic:**
Return the results of a specific jobId (if it exists in the database).

## **6. Update role permissions**
```
{
    "message": "An error occurred (AccessDeniedException) when calling the Query operation: User: arn:aws:sts::697074967465:assumed-role/FeMo-prototype-Deployment-InferenceAPIConstructInfe-dphYNXScTleL/FeMo-prototype-Deployment-InferenceAPIConstructInf-Zogh2vYFvxVu is not authorized to perform: dynamodb:Query on resource: arn:aws:dynamodb:eu-north-1:697074967465:table/FeMo-prototype-DeploymentStack-InferenceResultTable98290E39-PVV6K9RHRXGH/index/JobIdIndex because no identity-based policy allows the dynamodb:Query action"
}
```
