### ISSUE TITLE
Github actions workflow

### ISSUE THREAD

**Issue by MABatin** [MAIMLab-DU/FeMo_MLOps-CDK#6]
#### **Description**
To ensure proper deployment of the CDK apps and infrastructure, implement a GitHub Actions workflow to handle deployment and triggering of pipelines. The workflow should:
- Deploy the `infrastructureStack` when there are changes in the `infrastructure` folder.
- Trigger the **Deploy** project in CodePipeline for updates in the `model_deploy` folder.
- Separate stacks for `dev` and `prod` stages to handle different deployment environments.
- Branch for `dev` = **dev** and `prod` = **main**
- Ingest and use separate `projectConfig.json` files for `dev` and `prod` stages.

This ensures proper CI/CD for the project and enforces stage-specific configurations.

---

#### **Tasks**
- [x] ~**Add CI Check for the Project**:~
  - ~Run basic linting, testing, and validation for the CDK codebase on every push.~
  - ~Might be redundant but ensures code quality.~

- [x] **Workflow for Deploying `infrastructureStack`**:
  - [x] Trigger deployment when there are changes in the `infrastructure` folder.
  - [x] Use AWS CDK commands to deploy only the infrastructure stack.
  - [x] Implement a pipeline execution workflow to automatically deploy the infrastructure.

- [x] ~**Workflow for Triggering CodePipeline**:~
  - [x] ~Trigger the **Deploy** project in CodePipeline when there are changes in the `model_deploy` folder.~
  - [x] ~Add environment validation before triggering the pipeline.~

- [x] **Set Different Parameters for Stages**:
  - Define and set stage-specific parameters (`dev` and `prod`) for the `infrastructureStack` and `model_deployStack`.
  - Examples:
    - `dev` stage might use smaller instance sizes and throttling limits.
    - `prod` stage might use larger resources and stricter policies.
- [x] **Different `projectConfig.json` file for different environments (hence different stacks)'**

- [x] Path to project config file as CDK parameter

- [x] **Test Workflows**:
  - Validate that the workflows properly trigger deployments and pipelines for both `dev` and `prod`.
  - Ensure configurations are correctly applied for each stage.

---

#### **Implementation Notes**
1. **Infrastructure Deployment Workflow**:
   - Use CDK CLI commands:
     ```yaml
     - name: Deploy Infrastructure Stack
       run: cdk deploy --app path/to/infrastructure
     ```

2. **Trigger CodePipeline**:
   - Use AWS CLI to trigger the pipeline:
     ```yaml
     - name: Trigger CodePipeline
       run: aws codepipeline start-pipeline-execution --name YourPipelineName
     ```

4. Store `projectConfig.json` in Github [as base64](https://blog.devgenius.io/saving-jsons-as-github-secrets-and-accessing-values-from-actions-7d3bdbbc7d28)
